name: D-Robo Setup
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Git and Clone Setup Repository
        shell: bash
        run: |
          sudo apt update
          sudo apt -y install git
          cd ~/
          git clone https://github.com/nityc-d-robo/setup_d-robo.git
          chmod +x ./setup_d-robo/*
          . ./setup_d-robo/start.sh
